import type { Metadata } from "next";
import "./globals.css";
import {Header} from "@/components/header";
import { Providers } from "@/providers/providers";
import { JetBrains_Mono } from 'next/font/google'


// import { Roboto } from 'next/font/google'
// import { Jet } from 'next/font/google'

 
// const roboto = Roboto({
//   weight: '400',
//   subsets: ['latin'],
// })

const jetbrainsMono = JetBrains_Mono({
  weight: '400',
  subsets: ['latin',],
})
export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by Ansh Jain",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.className} antialiased`}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
