import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header/header";
import { Providers } from "@/providers/providers";
import { JetBrains_Mono } from "next/font/google";
import { cn } from "@/lib/utils";
import { Suspense } from "react";
import Footer from "@/components/common/footer";
import { getCustomSession } from "@/lib/session";
import { Toaster } from "sonner";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: {
    default: "Next App",
    template: "CodeSnipper | Next App",
  },
  description: "Generated by Ansh Jain",
  keywords: ["Next.js", "Drizzle", "Turso", "Ansh Jain"],
  authors: [{ name: "Ansh Jain" }],
  openGraph: {
    title: "Next App",
    description: "Generated by Ansh Jain",
    type: "website",
    locale: "en_US",
    siteName: "Next App",
  },
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Get initial session for the custom session provider
  const initialSession = await getCustomSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen antialiased", jetbrainsMono.className)}>
        <Providers initialSession={initialSession}>
          <Header />
          <main className="mx-auto">
            <Suspense
              fallback={<div className="text-center py-10">Loading...</div>}
            >
              {children}
              <Toaster position="top-right" richColors />
            </Suspense>
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
